language: python

python:
  - "3.7"

sudo: false

install:
  - pip install -r requirements.txt

script:
  - mkdir doc-src/_static; cd doc-src; sphinx-build -nW -b html -D exclude_patterns=dev/docs/templates/*  -d _build/doctrees . _build/html

notifications:
  email: false
